/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: incident.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "incident.pb-c.h"
void   key_incident__init
                     (KeyIncident         *message)
{
  static const KeyIncident init_value = KEY_INCIDENT__INIT;
  *message = init_value;
}
size_t key_incident__get_packed_size
                     (const KeyIncident *message)
{
  assert(message->base.descriptor == &key_incident__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t key_incident__pack
                     (const KeyIncident *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &key_incident__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t key_incident__pack_to_buffer
                     (const KeyIncident *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &key_incident__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
KeyIncident *
       key_incident__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (KeyIncident *)
     protobuf_c_message_unpack (&key_incident__descriptor,
                                allocator, len, data);
}
void   key_incident__free_unpacked
                     (KeyIncident *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &key_incident__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor key_incident__field_descriptors[10] =
{
  {
    "sip",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(KeyIncident, sip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dip",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(KeyIncident, dip),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "sport",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(KeyIncident, sport),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dport",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(KeyIncident, dport),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "smac",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(KeyIncident, smac),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "dmac",
    6,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(KeyIncident, dmac),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "proto",
    7,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(KeyIncident, proto),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "app",
    8,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(KeyIncident, app),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "flow_time",
    9,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(KeyIncident, flow_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pkt_time",
    10,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(KeyIncident, pkt_time),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned key_incident__field_indices_by_name[] = {
  7,   /* field[7] = app */
  1,   /* field[1] = dip */
  5,   /* field[5] = dmac */
  3,   /* field[3] = dport */
  8,   /* field[8] = flow_time */
  9,   /* field[9] = pkt_time */
  6,   /* field[6] = proto */
  0,   /* field[0] = sip */
  4,   /* field[4] = smac */
  2,   /* field[2] = sport */
};
static const ProtobufCIntRange key_incident__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 10 }
};
const ProtobufCMessageDescriptor key_incident__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "key_incident",
  "KeyIncident",
  "KeyIncident",
  "",
  sizeof(KeyIncident),
  10,
  key_incident__field_descriptors,
  key_incident__field_indices_by_name,
  1,  key_incident__number_ranges,
  (ProtobufCMessageInit) key_incident__init,
  NULL,NULL,NULL    /* reserved[123] */
};
