/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: incident.proto */

#ifndef PROTOBUF_C_incident_2eproto__INCLUDED
#define PROTOBUF_C_incident_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1003001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _KeyIncident KeyIncident;


/* --- enums --- */


/* --- messages --- */

struct  _KeyIncident
{
  ProtobufCMessage base;
  char *sip;
  char *dip;
  int32_t sport;
  int32_t dport;
  char *smac;
  char *dmac;
  char *proto;
  char *app;
  char *flow_time;
  char *pkt_time;
};
#define KEY_INCIDENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&key_incident__descriptor) \
    , NULL, NULL, 0, 0, NULL, NULL, NULL, NULL, NULL, NULL }


/* KeyIncident methods */
void   key_incident__init
                     (KeyIncident         *message);
size_t key_incident__get_packed_size
                     (const KeyIncident   *message);
size_t key_incident__pack
                     (const KeyIncident   *message,
                      uint8_t             *out);
size_t key_incident__pack_to_buffer
                     (const KeyIncident   *message,
                      ProtobufCBuffer     *buffer);
KeyIncident *
       key_incident__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   key_incident__free_unpacked
                     (KeyIncident *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*KeyIncident_Closure)
                 (const KeyIncident *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor key_incident__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_incident_2eproto__INCLUDED */
